// Curated topical cross-references — "I feel X, what does Scripture say" — grouped by
// life situation/emotion. Only book/chapter/verse are stored; the verse text itself is
// looked up live from whichever Bible translation is already downloaded (database/bible.ts),
// the same lazy-load-nothing-twice approach used everywhere else in this app.
export type TopicalVerseRef = { book: string; chapter: number; verseStart: number; verseEnd?: number };
export type Topic = { key: string; label: string; verses: TopicalVerseRef[] };

export const TOPICS: Topic[] = [
  {
    key: 'anxiety',
    label: 'Anxiety & Worry',
    verses: [
      { book: 'Philippians', chapter: 4, verseStart: 6, verseEnd: 7 },
      { book: 'Matthew', chapter: 6, verseStart: 25, verseEnd: 27 },
      { book: '1 Peter', chapter: 5, verseStart: 7 },
      { book: 'Psalms', chapter: 94, verseStart: 19 },
      { book: 'John', chapter: 14, verseStart: 27 },
      { book: 'Isaiah', chapter: 41, verseStart: 10 },
      { book: 'Psalms', chapter: 55, verseStart: 22 },
    ],
  },
  {
    key: 'depression',
    label: 'Depression & Despair',
    verses: [
      { book: 'Psalms', chapter: 34, verseStart: 17, verseEnd: 18 },
      { book: 'Psalms', chapter: 42, verseStart: 5, verseEnd: 6 },
      { book: 'Psalms', chapter: 40, verseStart: 1, verseEnd: 3 },
      { book: 'Isaiah', chapter: 43, verseStart: 1, verseEnd: 3 },
      { book: '2 Corinthians', chapter: 4, verseStart: 8, verseEnd: 9 },
      { book: 'Lamentations', chapter: 3, verseStart: 22, verseEnd: 23 },
      { book: 'Psalms', chapter: 147, verseStart: 3 },
    ],
  },
  {
    key: 'anger',
    label: 'Anger',
    verses: [
      { book: 'Ephesians', chapter: 4, verseStart: 26, verseEnd: 27 },
      { book: 'James', chapter: 1, verseStart: 19, verseEnd: 20 },
      { book: 'Proverbs', chapter: 15, verseStart: 1 },
      { book: 'Proverbs', chapter: 29, verseStart: 11 },
      { book: 'Colossians', chapter: 3, verseStart: 8 },
      { book: 'Ecclesiastes', chapter: 7, verseStart: 9 },
      { book: 'Psalms', chapter: 37, verseStart: 8 },
    ],
  },
  {
    key: 'grief',
    label: 'Grief & Loss (Funeral)',
    verses: [
      { book: 'Revelation', chapter: 21, verseStart: 4 },
      { book: 'Psalms', chapter: 34, verseStart: 18 },
      { book: 'Matthew', chapter: 5, verseStart: 4 },
      { book: '1 Thessalonians', chapter: 4, verseStart: 13, verseEnd: 14 },
      { book: 'John', chapter: 11, verseStart: 25, verseEnd: 26 },
      { book: '2 Corinthians', chapter: 1, verseStart: 3, verseEnd: 4 },
      { book: 'Psalms', chapter: 23, verseStart: 1, verseEnd: 4 },
      { book: 'Isaiah', chapter: 25, verseStart: 8 },
    ],
  },
  {
    key: 'wedding',
    label: 'Wedding & Marriage',
    verses: [
      { book: '1 Corinthians', chapter: 13, verseStart: 4, verseEnd: 7 },
      { book: 'Ecclesiastes', chapter: 4, verseStart: 9, verseEnd: 12 },
      { book: 'Song of Solomon', chapter: 8, verseStart: 6, verseEnd: 7 },
      { book: 'Genesis', chapter: 2, verseStart: 24 },
      { book: 'Ephesians', chapter: 5, verseStart: 25, verseEnd: 33 },
      { book: 'Colossians', chapter: 3, verseStart: 14 },
      { book: 'Proverbs', chapter: 18, verseStart: 22 },
    ],
  },
  {
    key: 'joy',
    label: 'Happiness & Joy',
    verses: [
      { book: 'Nehemiah', chapter: 8, verseStart: 10 },
      { book: 'Philippians', chapter: 4, verseStart: 4 },
      { book: 'Psalms', chapter: 16, verseStart: 11 },
      { book: 'John', chapter: 15, verseStart: 11 },
      { book: 'Psalms', chapter: 30, verseStart: 5 },
      { book: 'James', chapter: 1, verseStart: 2, verseEnd: 3 },
      { book: 'Galatians', chapter: 5, verseStart: 22, verseEnd: 23 },
    ],
  },
  {
    key: 'fear',
    label: 'Fear',
    verses: [
      { book: '2 Timothy', chapter: 1, verseStart: 7 },
      { book: 'Isaiah', chapter: 41, verseStart: 10 },
      { book: 'Psalms', chapter: 27, verseStart: 1 },
      { book: 'Joshua', chapter: 1, verseStart: 9 },
      { book: 'Psalms', chapter: 23, verseStart: 4 },
      { book: '1 John', chapter: 4, verseStart: 18 },
      { book: 'Deuteronomy', chapter: 31, verseStart: 6 },
    ],
  },
  {
    key: 'forgiveness',
    label: 'Forgiveness',
    verses: [
      { book: 'Matthew', chapter: 6, verseStart: 14, verseEnd: 15 },
      { book: 'Ephesians', chapter: 4, verseStart: 32 },
      { book: 'Colossians', chapter: 3, verseStart: 13 },
      { book: '1 John', chapter: 1, verseStart: 9 },
      { book: 'Luke', chapter: 6, verseStart: 37 },
      { book: 'Psalms', chapter: 103, verseStart: 12 },
      { book: 'Matthew', chapter: 18, verseStart: 21, verseEnd: 22 },
    ],
  },
  {
    key: 'guidance',
    label: 'Guidance & Decisions',
    verses: [
      { book: 'Proverbs', chapter: 3, verseStart: 5, verseEnd: 6 },
      { book: 'James', chapter: 1, verseStart: 5 },
      { book: 'Psalms', chapter: 32, verseStart: 8 },
      { book: 'Psalms', chapter: 119, verseStart: 105 },
      { book: 'Isaiah', chapter: 30, verseStart: 21 },
      { book: 'Proverbs', chapter: 16, verseStart: 3 },
      { book: 'Jeremiah', chapter: 29, verseStart: 11 },
    ],
  },
  {
    key: 'strength',
    label: 'Strength in Weakness',
    verses: [
      { book: 'Philippians', chapter: 4, verseStart: 13 },
      { book: 'Isaiah', chapter: 40, verseStart: 29, verseEnd: 31 },
      { book: '2 Corinthians', chapter: 12, verseStart: 9, verseEnd: 10 },
      { book: 'Psalms', chapter: 46, verseStart: 1 },
      { book: 'Nehemiah', chapter: 8, verseStart: 10 },
      { book: 'Deuteronomy', chapter: 31, verseStart: 6 },
      { book: 'Ephesians', chapter: 6, verseStart: 10 },
    ],
  },
  {
    key: 'patience',
    label: 'Patience',
    verses: [
      { book: 'Romans', chapter: 12, verseStart: 12 },
      { book: 'James', chapter: 1, verseStart: 3, verseEnd: 4 },
      { book: 'Galatians', chapter: 6, verseStart: 9 },
      { book: 'Psalms', chapter: 27, verseStart: 14 },
      { book: 'Ecclesiastes', chapter: 3, verseStart: 1 },
      { book: 'Colossians', chapter: 3, verseStart: 12 },
      { book: 'Isaiah', chapter: 40, verseStart: 31 },
    ],
  },
  {
    key: 'love',
    label: 'Love',
    verses: [
      { book: '1 Corinthians', chapter: 13, verseStart: 4, verseEnd: 8 },
      { book: 'John', chapter: 3, verseStart: 16 },
      { book: 'John', chapter: 13, verseStart: 34, verseEnd: 35 },
      { book: '1 John', chapter: 4, verseStart: 7, verseEnd: 8 },
      { book: 'Romans', chapter: 5, verseStart: 8 },
      { book: '1 John', chapter: 4, verseStart: 19 },
      { book: 'Romans', chapter: 8, verseStart: 38, verseEnd: 39 },
    ],
  },
  {
    key: 'hope',
    label: 'Hope',
    verses: [
      { book: 'Jeremiah', chapter: 29, verseStart: 11 },
      { book: 'Romans', chapter: 15, verseStart: 13 },
      { book: 'Romans', chapter: 8, verseStart: 28 },
      { book: 'Psalms', chapter: 39, verseStart: 7 },
      { book: 'Lamentations', chapter: 3, verseStart: 21, verseEnd: 24 },
      { book: 'Hebrews', chapter: 11, verseStart: 1 },
      { book: 'Romans', chapter: 5, verseStart: 3, verseEnd: 5 },
    ],
  },
  {
    key: 'loneliness',
    label: 'Loneliness',
    verses: [
      { book: 'Deuteronomy', chapter: 31, verseStart: 8 },
      { book: 'Hebrews', chapter: 13, verseStart: 5 },
      { book: 'Psalms', chapter: 68, verseStart: 6 },
      { book: 'Isaiah', chapter: 41, verseStart: 10 },
      { book: 'Psalms', chapter: 25, verseStart: 16, verseEnd: 17 },
      { book: 'Matthew', chapter: 28, verseStart: 20 },
      { book: 'John', chapter: 14, verseStart: 18 },
    ],
  },
  {
    key: 'temptation',
    label: 'Temptation',
    verses: [
      { book: '1 Corinthians', chapter: 10, verseStart: 13 },
      { book: 'James', chapter: 1, verseStart: 12, verseEnd: 14 },
      { book: 'Matthew', chapter: 26, verseStart: 41 },
      { book: 'Hebrews', chapter: 2, verseStart: 18 },
      { book: 'Hebrews', chapter: 4, verseStart: 15, verseEnd: 16 },
      { book: 'James', chapter: 4, verseStart: 7 },
      { book: 'Psalms', chapter: 119, verseStart: 11 },
    ],
  },
  {
    key: 'healing',
    label: 'Healing & Sickness',
    verses: [
      { book: 'James', chapter: 5, verseStart: 14, verseEnd: 15 },
      { book: 'Psalms', chapter: 103, verseStart: 2, verseEnd: 3 },
      { book: 'Jeremiah', chapter: 17, verseStart: 14 },
      { book: 'Isaiah', chapter: 53, verseStart: 5 },
      { book: 'Exodus', chapter: 15, verseStart: 26 },
      { book: 'Psalms', chapter: 30, verseStart: 2 },
      { book: '3 John', chapter: 1, verseStart: 2 },
    ],
  },
  {
    key: 'finances',
    label: 'Finances & Provision',
    verses: [
      { book: 'Philippians', chapter: 4, verseStart: 19 },
      { book: 'Matthew', chapter: 6, verseStart: 33 },
      { book: 'Malachi', chapter: 3, verseStart: 10 },
      { book: 'Proverbs', chapter: 3, verseStart: 9, verseEnd: 10 },
      { book: '2 Corinthians', chapter: 9, verseStart: 6, verseEnd: 8 },
      { book: 'Psalms', chapter: 37, verseStart: 25 },
      { book: 'Hebrews', chapter: 13, verseStart: 5 },
    ],
  },
  {
    key: 'parenting',
    label: 'Parenting & Children',
    verses: [
      { book: 'Proverbs', chapter: 22, verseStart: 6 },
      { book: 'Ephesians', chapter: 6, verseStart: 4 },
      { book: 'Deuteronomy', chapter: 6, verseStart: 6, verseEnd: 7 },
      { book: 'Psalms', chapter: 127, verseStart: 3 },
      { book: 'Proverbs', chapter: 29, verseStart: 17 },
      { book: 'Colossians', chapter: 3, verseStart: 21 },
      { book: '3 John', chapter: 1, verseStart: 4 },
    ],
  },
  {
    key: 'comfort',
    label: 'Comfort & Encouragement',
    verses: [
      { book: '2 Corinthians', chapter: 1, verseStart: 3, verseEnd: 4 },
      { book: 'Matthew', chapter: 11, verseStart: 28, verseEnd: 30 },
      { book: 'Psalms', chapter: 34, verseStart: 18 },
      { book: 'Isaiah', chapter: 66, verseStart: 13 },
      { book: 'Psalms', chapter: 147, verseStart: 3 },
      { book: 'John', chapter: 14, verseStart: 1 },
      { book: 'Psalms', chapter: 73, verseStart: 26 },
    ],
  },
  {
    key: 'faith_doubt',
    label: 'Faith & Doubt',
    verses: [
      { book: 'Hebrews', chapter: 11, verseStart: 1 },
      { book: 'Mark', chapter: 9, verseStart: 24 },
      { book: 'Matthew', chapter: 17, verseStart: 20 },
      { book: 'Romans', chapter: 10, verseStart: 17 },
      { book: 'James', chapter: 1, verseStart: 6 },
      { book: '2 Corinthians', chapter: 5, verseStart: 7 },
      { book: 'John', chapter: 20, verseStart: 29 },
    ],
  },
  {
    key: 'peace',
    label: 'Peace',
    verses: [
      { book: 'John', chapter: 14, verseStart: 27 },
      { book: 'Philippians', chapter: 4, verseStart: 6, verseEnd: 7 },
      { book: 'Isaiah', chapter: 26, verseStart: 3 },
      { book: 'Colossians', chapter: 3, verseStart: 15 },
      { book: 'Numbers', chapter: 6, verseStart: 24, verseEnd: 26 },
      { book: 'Psalms', chapter: 29, verseStart: 11 },
      { book: 'Romans', chapter: 15, verseStart: 13 },
    ],
  },
  {
    key: 'gratitude',
    label: 'Gratitude & Thankfulness',
    verses: [
      { book: '1 Thessalonians', chapter: 5, verseStart: 16, verseEnd: 18 },
      { book: 'Psalms', chapter: 100, verseStart: 4, verseEnd: 5 },
      { book: 'Colossians', chapter: 3, verseStart: 17 },
      { book: 'Philippians', chapter: 4, verseStart: 6 },
      { book: 'Psalms', chapter: 107, verseStart: 1 },
      { book: 'James', chapter: 1, verseStart: 17 },
      { book: 'Psalms', chapter: 95, verseStart: 2 },
    ],
  },
  {
    key: 'perseverance',
    label: 'Perseverance & Trials',
    verses: [
      { book: 'James', chapter: 1, verseStart: 2, verseEnd: 4 },
      { book: 'Romans', chapter: 5, verseStart: 3, verseEnd: 4 },
      { book: 'Galatians', chapter: 6, verseStart: 9 },
      { book: '2 Corinthians', chapter: 4, verseStart: 16, verseEnd: 18 },
      { book: 'Hebrews', chapter: 12, verseStart: 1, verseEnd: 2 },
      { book: '1 Peter', chapter: 5, verseStart: 10 },
      { book: 'Romans', chapter: 8, verseStart: 18 },
    ],
  },
  {
    key: 'salvation',
    label: 'Salvation & New Life',
    verses: [
      { book: 'John', chapter: 3, verseStart: 16 },
      { book: 'Romans', chapter: 10, verseStart: 9, verseEnd: 10 },
      { book: 'Ephesians', chapter: 2, verseStart: 8, verseEnd: 9 },
      { book: '2 Corinthians', chapter: 5, verseStart: 17 },
      { book: 'Romans', chapter: 6, verseStart: 23 },
      { book: 'Acts', chapter: 4, verseStart: 12 },
      { book: 'Revelation', chapter: 3, verseStart: 20 },
    ],
  },
  {
    key: 'sabbath_rest',
    label: 'Sabbath & Rest',
    verses: [
      { book: 'Exodus', chapter: 20, verseStart: 8, verseEnd: 11 },
      { book: 'Genesis', chapter: 2, verseStart: 2, verseEnd: 3 },
      { book: 'Mark', chapter: 2, verseStart: 27 },
      { book: 'Isaiah', chapter: 58, verseStart: 13, verseEnd: 14 },
      { book: 'Matthew', chapter: 11, verseStart: 28 },
      { book: 'Hebrews', chapter: 4, verseStart: 9, verseEnd: 10 },
    ],
  },
];
